import { ArrowRight, BarChart3, CheckCircle2, CreditCard, Gift, LineChart, Megaphone, ShieldCheck, Sparkles, Store, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";

interface DesktopMarketingPrototypeProps { screenId: string; }

const BrowserTop = () => <header className="flex items-center justify-between border-b border-border bg-card px-8 py-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-primary text-primary-foreground"><Sparkles className="h-5 w-5" /></div><span className="text-xl font-black">PerkBack</span></div><nav className="hidden items-center gap-7 text-sm font-bold text-muted-foreground lg:flex"><span>Merchants</span><span>Customers</span><span>Pricing</span><span>Resources</span></nav><Button className="rounded-full">Start free</Button></header>;
const Stat = ({ label, value }: { label: string; value: string }) => <div className="rounded-2xl border border-border bg-card p-5 shadow-card"><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>;
const Chart = () => <div className="flex h-52 items-end gap-3 rounded-2xl bg-muted/50 p-5">{[36, 58, 45, 72, 64, 88, 78, 96].map((height, index) => <span key={index} className="flex-1 rounded-t-xl bg-gradient-primary" style={{ height: `${height}%` }} />)}</div>;

const Homepage = () => <><BrowserTop /><section className="grid min-h-[620px] gap-8 px-10 py-12 lg:grid-cols-[1.05fr_0.95fr]"><div className="flex flex-col justify-center"><div className="inline-flex w-fit items-center gap-2 rounded-full border border-border bg-card px-4 py-2 text-xs font-black uppercase tracking-[0.14em] text-muted-foreground shadow-card"><Sparkles className="h-4 w-4 text-accent-deep" /> Loyalty operating system</div><h2 className="mt-7 max-w-3xl text-6xl font-black leading-[0.95] tracking-tight">A premium rewards platform for local businesses.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">PerkBack helps cafés, retailers and restaurants grow repeat purchases with digital cards, points, campaigns and local discovery.</p><div className="mt-8 flex gap-3"><Button size="lg" className="rounded-full">Start free <ArrowRight className="h-4 w-4" /></Button><Button size="lg" variant="outline" className="rounded-full">View demo</Button></div></div><div className="relative rounded-[2rem] bg-gradient-hero p-6 text-primary-foreground shadow-hero"><div className="rounded-[1.5rem] bg-primary-foreground/10 p-5 backdrop-blur"><p className="text-sm text-primary-foreground/70">Bean Society</p><p className="mt-1 text-4xl font-black">$8,420 retained</p><Chart /></div><div className="mt-4 grid grid-cols-3 gap-3"><Stat label="Repeat" value="38%" /><Stat label="Rewards" value="214" /><Stat label="Campaigns" value="9" /></div></div></section></>;

const Pricing = () => <><BrowserTop /><section className="px-10 py-12"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow">Pricing</p><h2 className="mt-2 text-5xl font-black">Start free, grow when loyalty works.</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{[["Free", "$0", "Launch digital cards"], ["Growth", "$49", "Campaigns and analytics"], ["Pro", "$129", "Automation and priority support"]].map(([name, price, body], i) => <div key={name} className={`rounded-[2rem] border p-6 shadow-card ${i === 1 ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card"}`}><p className="text-xl font-black">{name}</p><p className="mt-5 text-5xl font-black">{price}</p><p className={`mt-2 text-sm ${i === 1 ? "text-primary-foreground/75" : "text-muted-foreground"}`}>{body}</p><div className="mt-8 space-y-3">{["Digital loyalty cards", "Merchant dashboard", "Rewards and offers", "Customer segments"].map((feature) => <p key={feature} className="flex items-center gap-2 text-sm font-bold"><CheckCircle2 className="h-4 w-4" /> {feature}</p>)}</div><Button variant={i === 1 ? "gold" : "default"} className="mt-8 w-full rounded-full">Choose {name}</Button></div>)}</div></section></>;

const DesktopCustomer = () => <><BrowserTop /><section className="grid gap-6 px-10 py-8 lg:grid-cols-[17rem_1fr]"><aside className="rounded-2xl bg-card p-4 shadow-card"><p className="eyebrow">Customer</p><div className="mt-5 space-y-2">{[WalletCards, Gift, Store, CreditCard].map((Icon, i) => <div key={i} className={`flex items-center gap-3 rounded-xl p-3 font-bold ${i === 0 ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}><Icon className="h-4 w-4" /> Menu</div>)}</div></aside><div className="space-y-6"><div className="rounded-[2rem] bg-gradient-hero p-8 text-primary-foreground shadow-hero"><p className="text-primary-foreground/70">Mia Chen · Gold member</p><p className="mt-2 text-6xl font-black">2,840 points</p><div className="mt-6 h-3 rounded-full bg-primary-foreground/20"><div className="h-3 w-3/4 rounded-full bg-accent" /></div></div><div className="grid gap-4 lg:grid-cols-3"><Stat label="Ready rewards" value="7" /><Stat label="Nearby stores" value="12" /><Stat label="This month" value="+420" /></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-card p-6 shadow-card"><h3 className="text-xl font-black">Rewards marketplace</h3><p className="mt-2 text-muted-foreground">Coffee, retail and restaurant perks ready to redeem.</p></div><div className="rounded-2xl bg-card p-6 shadow-card"><h3 className="text-xl font-black">Recent receipts</h3><p className="mt-2 text-muted-foreground">See points earned on every participating purchase.</p></div></div></div></section></>;

export const DesktopMarketingPrototype = ({ screenId }: DesktopMarketingPrototypeProps) => {
  if (screenId === "marketing-pricing") return <Pricing />;
  if (screenId === "desktop-customer") return <DesktopCustomer />;
  return <Homepage />;
};
