import { BarChart3, Bell, Gift, LineChart, Megaphone, Settings, ShieldCheck, Store, Users } from "lucide-react";
import { Button } from "@/components/ui/button";

interface DesktopDashboardPrototypeProps { screenId: string; }

const Shell = ({ children }: { children: React.ReactNode }) => <div className="grid min-h-[680px] grid-cols-[16rem_1fr] bg-background"><aside className="border-r border-border bg-card p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-primary text-primary-foreground"><Store className="h-5 w-5" /></div><span className="font-black">PerkBack OS</span></div><div className="mt-8 space-y-2">{[BarChart3, Users, Gift, Megaphone, LineChart, Settings].map((Icon, i) => <div key={i} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${i === 0 ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}><Icon className="h-4 w-4" /> Dashboard</div>)}</div></aside><main className="p-8">{children}</main></div>;
const Stat = ({ label, value, delta }: { label: string; value: string; delta: string }) => <div className="rounded-2xl bg-card p-5 shadow-card"><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-2 text-sm font-bold text-success">{delta}</p></div>;
const Bars = () => <div className="flex h-64 items-end gap-3 rounded-2xl bg-muted/50 p-5">{[42, 56, 48, 80, 70, 92, 84, 98, 76, 90].map((height, index) => <span key={index} className="flex-1 rounded-t-xl bg-gradient-primary" style={{ height: `${height}%` }} />)}</div>;

const Merchant = () => <Shell><div className="flex items-center justify-between"><div><p className="eyebrow">Bean Society</p><h2 className="text-4xl font-black">Merchant loyalty dashboard</h2></div><Button className="rounded-full">Add points</Button></div><div className="mt-8 grid gap-4 lg:grid-cols-4"><Stat label="Revenue tracked" value="$8.4k" delta="+18%" /><Stat label="Repeat customers" value="38%" delta="+6%" /><Stat label="Points issued" value="18.2k" delta="+2.4k" /><Stat label="Rewards used" value="214" delta="+31" /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_22rem]"><div className="rounded-2xl bg-card p-6 shadow-card"><h3 className="text-xl font-black">Retention trend</h3><Bars /></div><div className="space-y-4"><div className="rounded-2xl bg-gradient-hero p-6 text-primary-foreground shadow-hero"><Megaphone className="h-6 w-6" /><h3 className="mt-5 text-2xl font-black">Double points window</h3><p className="mt-2 text-sm text-primary-foreground/75">Best action for slow afternoon trade.</p></div><div className="rounded-2xl bg-card p-6 shadow-card"><h3 className="font-black">Live activity</h3><p className="mt-3 text-sm text-muted-foreground">Mia earned 42 points · Oscar redeemed free coffee</p></div></div></div></Shell>;
const Analytics = () => <Shell><div className="flex items-center justify-between"><div><p className="eyebrow">Analytics</p><h2 className="text-4xl font-black">Understand loyalty impact</h2></div><Button variant="outline" className="rounded-full">Export report</Button></div><div className="mt-8 grid gap-4 lg:grid-cols-3"><Stat label="Retained revenue" value="$24.8k" delta="+21%" /><Stat label="At-risk saved" value="86" delta="+14" /><Stat label="Campaign ROI" value="4.8x" delta="+0.9x" /></div><div className="mt-6 rounded-2xl bg-card p-6 shadow-card"><h3 className="text-xl font-black">Segment movement</h3><Bars /></div></Shell>;
const Admin = () => <Shell><div className="flex items-center justify-between"><div><p className="eyebrow">Platform</p><h2 className="text-4xl font-black">Merchant health overview</h2></div><Bell className="h-6 w-6 text-muted-foreground" /></div><div className="mt-8 grid gap-4 lg:grid-cols-4"><Stat label="Active merchants" value="248" delta="+12" /><Stat label="Customers" value="18.4k" delta="+1.2k" /><Stat label="Transactions" value="92k" delta="+18%" /><Stat label="Platform NPS" value="68" delta="+4" /></div><div className="mt-6 grid gap-4 lg:grid-cols-3">{["Coffee shops", "Retail", "Restaurants"].map((name) => <div key={name} className="rounded-2xl bg-card p-6 shadow-card"><ShieldCheck className="h-6 w-6 text-success" /><h3 className="mt-4 text-xl font-black">{name}</h3><p className="mt-2 text-sm text-muted-foreground">Healthy retention and campaign engagement.</p></div>)}</div></Shell>;

export const DesktopDashboardPrototype = ({ screenId }: DesktopDashboardPrototypeProps) => {
  if (screenId === "desktop-analytics") return <Analytics />;
  if (screenId === "desktop-admin") return <Admin />;
  return <Merchant />;
};
