import { Camera, CheckCircle2, CreditCard, Gift, QrCode, Search, Sparkles, Store, UserRound, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";

interface MerchantTabletPrototypeProps {
  screenId: string;
}

const TabletPage = ({ children }: { children: React.ReactNode }) => <div className="min-h-[680px] bg-background p-6 text-foreground">{children}</div>;
const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-2xl bg-card p-4 shadow-card"><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>;
const CustomerChip = () => <div className="flex items-center gap-3 rounded-2xl bg-muted p-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground"><UserRound className="h-5 w-5" /></div><div><p className="font-black">Mia Chen</p><p className="text-sm text-muted-foreground">Gold · CRN 48291 · 2,840 pts</p></div></div>;

const Counter = () => <TabletPage><div className="flex items-start justify-between"><div><p className="eyebrow">Bean Society counter</p><h2 className="mt-1 text-4xl font-black">Fast loyalty actions</h2></div><div className="rounded-full bg-success/15 px-4 py-2 text-sm font-black text-success">POS connected</div></div><div className="mt-8 grid gap-4 md:grid-cols-4"><Metric label="Today revenue" value="$842" /><Metric label="Customers" value="42" /><Metric label="Points" value="1.8k" /><Metric label="Rewards" value="14" /></div><div className="mt-8 grid gap-5 md:grid-cols-3">{[[QrCode, "Scan card", "Use QR, barcode or NFC"], [Gift, "Add points", "Enter purchase amount"], [Users, "Find customer", "Phone, CRN or card"]].map(([Icon, title, body]) => <div key={String(title)} className="rounded-[2rem] bg-card p-6 shadow-card"><Icon className="h-8 w-8 text-primary" /><h3 className="mt-8 text-2xl font-black">{String(title)}</h3><p className="mt-2 text-sm text-muted-foreground">{String(body)}</p></div>)}</div></TabletPage>;
const Scan = () => <TabletPage><div className="grid min-h-[620px] gap-6 md:grid-cols-[1.1fr_0.9fr]"><div className="relative overflow-hidden rounded-[2rem] bg-foreground shadow-hero"><Camera className="absolute left-1/2 top-1/2 h-24 w-24 -translate-x-1/2 -translate-y-1/2 text-background/50" /><div className="absolute inset-16 rounded-[2rem] border-2 border-accent" /><div className="animate-scan-line absolute left-16 right-16 h-0.5 bg-accent" /></div><div className="flex flex-col justify-center"><p className="eyebrow">Scan customer</p><h2 className="mt-1 text-4xl font-black">Point camera at loyalty QR</h2><div className="mt-6 flex items-center gap-2 rounded-full bg-card px-4 py-3 shadow-card"><Search className="h-4 w-4 text-muted-foreground" /><span className="text-sm text-muted-foreground">Or search phone, CRN, card number</span></div><Button className="mt-6 h-12 rounded-full">Use matched customer</Button></div></div></TabletPage>;
const AddPoints = () => <TabletPage><div className="grid gap-6 md:grid-cols-[1fr_1fr]"><div><p className="eyebrow">Customer lookup</p><h2 className="mt-1 text-4xl font-black">Add points</h2><div className="mt-6 rounded-[2rem] bg-card p-5 shadow-card"><CustomerChip /><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="Visits" value="12" /><Metric label="Balance" value="2.8k" /></div></div></div><div className="rounded-[2rem] bg-card p-6 shadow-card"><p className="eyebrow">Purchase</p><div className="mt-5 rounded-2xl bg-muted p-5"><p className="text-sm text-muted-foreground">Amount</p><p className="mt-2 text-6xl font-black">$18.40</p></div><div className="mt-4 rounded-2xl bg-gradient-gold p-5 text-accent-foreground"><p className="text-sm font-bold opacity-80">Points to issue</p><p className="mt-1 text-5xl font-black">+92</p></div><Button className="mt-5 h-12 w-full rounded-full">Review transaction</Button></div></div></TabletPage>;
const Confirm = () => <TabletPage><div className="mx-auto flex min-h-[620px] max-w-2xl flex-col justify-center"><p className="eyebrow">Confirm transaction</p><h2 className="mt-1 text-4xl font-black">Issue 92 points?</h2><div className="mt-6 rounded-[2rem] bg-card p-6 shadow-card"><CustomerChip /><div className="mt-6 space-y-3 text-lg"><div className="flex justify-between"><span>Purchase</span><strong>$18.40</strong></div><div className="flex justify-between"><span>Points</span><strong>+92</strong></div><div className="flex justify-between"><span>Next reward</span><strong>68 pts away</strong></div></div></div><Button className="mt-6 h-12 rounded-full">Confirm and send receipt</Button></div></TabletPage>;
const Success = () => <TabletPage><div className="mx-auto flex min-h-[620px] max-w-xl flex-col items-center justify-center text-center"><div className="flex h-24 w-24 items-center justify-center rounded-full bg-success/15 text-success"><CheckCircle2 className="h-12 w-12" /></div><h2 className="mt-6 text-4xl font-black">Points added</h2><p className="mt-3 text-muted-foreground">Mia earned 92 points and received a digital receipt.</p><div className="mt-6 w-full rounded-[2rem] bg-card p-6 shadow-card"><p className="font-black">68 points until free coffee</p><div className="mt-4 h-3 rounded-full bg-muted"><div className="h-3 w-4/5 rounded-full bg-primary" /></div></div><Button className="mt-6 h-12 rounded-full">Next customer</Button></div></TabletPage>;
const Customer = () => <TabletPage><div className="grid gap-6 md:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[2rem] bg-gradient-hero p-6 text-primary-foreground shadow-hero"><WalletCards className="h-8 w-8" /><h2 className="mt-20 text-4xl font-black">Mia Chen</h2><p className="mt-2 text-primary-foreground/75">Gold · 12 visits · $286 spend</p></div><div className="space-y-4"><Metric label="Points balance" value="2,932" /><div className="rounded-[2rem] bg-card p-5 shadow-card"><p className="font-black">Available rewards</p>{["Free coffee", "Birthday pastry", "Double points today"].map((item) => <div key={item} className="mt-3 flex items-center gap-3 rounded-2xl bg-muted p-3"><Gift className="h-5 w-5 text-accent-deep" /><span className="font-bold">{item}</span></div>)}</div><div className="rounded-[2rem] bg-card p-5 shadow-card"><Sparkles className="h-5 w-5 text-primary" /><p className="mt-3 font-black">Best action: offer pastry add-on</p></div></div></div></TabletPage>;

export const MerchantTabletPrototype = ({ screenId }: MerchantTabletPrototypeProps) => {
  const screens: Record<string, JSX.Element> = {
    "merchant-tablet-counter": <Counter />,
    "merchant-tablet-scan": <Scan />,
    "merchant-tablet-add-points": <AddPoints />,
    "merchant-tablet-confirm": <Confirm />,
    "merchant-tablet-success": <Success />,
    "merchant-tablet-customer": <Customer />,
  };
  return screens[screenId] ?? screens["merchant-tablet-counter"];
};
