import { BarChart3, Bell, Camera, CheckCircle2, ChevronRight, CreditCard, Gift, LineChart, Megaphone, QrCode, Search, Settings, Store, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";

interface MobileMerchantPrototypeProps { screenId: string; }

const PhonePage = ({ children }: { children: React.ReactNode }) => <div className="min-h-[760px] bg-background text-foreground"><div className="flex items-center justify-between px-5 pt-3 text-[11px] font-bold"><span>9:41</span><span className="h-2 w-5 rounded-sm bg-foreground/70" /></div>{children}</div>;
const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-2xl bg-card p-4 shadow-card"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>;
const Nav = () => <div className="absolute bottom-4 left-4 right-4 rounded-full border border-border bg-card/95 p-1 shadow-floating-nav"><div className="grid grid-cols-4 gap-1">{[BarChart3, Gift, Users, Settings].map((Icon, i) => <div key={i} className={`flex h-11 items-center justify-center rounded-full ${i === 0 ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}><Icon className="h-4 w-4" /></div>)}</div></div>;

const Login = () => <PhonePage><div className="px-5 py-8"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-primary text-primary-foreground shadow-button"><Store className="h-8 w-8" /></div><h2 className="mt-8 text-3xl font-black">Run loyalty from the counter.</h2><p className="mt-3 text-sm text-muted-foreground">Fast merchant tools for points, campaigns and customer retention.</p><div className="mt-8 space-y-3"><div className="rounded-2xl bg-card p-4 shadow-card"><p className="text-xs text-muted-foreground">Business email</p><p className="font-bold">owner@beansociety.com</p></div><div className="rounded-2xl bg-card p-4 shadow-card"><p className="text-xs text-muted-foreground">Password</p><p className="font-bold">••••••••</p></div></div><Button className="mt-6 h-12 w-full rounded-full">Open dashboard</Button></div></PhonePage>;
const Dashboard = () => <PhonePage><div className="relative min-h-[720px] px-5 pb-24 pt-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Bean Society</p><h2 className="text-2xl font-black">Today’s loyalty ROI</h2></div><Bell className="h-5 w-5" /></div><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="Revenue tracked" value="$842" /><Metric label="Repeat visits" value="38%" /><Metric label="Points issued" value="1.8k" /><Metric label="Rewards used" value="14" /></div><div className="mt-5 rounded-2xl bg-gradient-hero p-5 text-primary-foreground shadow-hero"><p className="font-black">Next best action</p><p className="mt-2 text-sm text-primary-foreground/75">Launch a double-points coffee hour between 2–4 PM.</p><Button size="sm" variant="gold" className="mt-4 rounded-full">Create campaign</Button></div><Nav /></div></PhonePage>;
const AddPoints = () => <PhonePage><div className="relative min-h-[720px] px-5 pb-24 pt-5"><p className="eyebrow">Add points</p><h2 className="text-2xl font-black">Customer purchase</h2><div className="mt-5 rounded-2xl bg-card p-4 shadow-card"><div className="flex items-center gap-3 rounded-xl bg-muted px-3 py-3"><Search className="h-4 w-4 text-muted-foreground" /><span className="text-sm text-muted-foreground">Search phone, CRN or card</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">Spend</p><p className="text-xl font-black">$18.40</p></div><div className="rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">Points</p><p className="text-xl font-black">+92</p></div></div><Button className="mt-4 h-12 w-full rounded-full">Add points</Button></div><Nav /></div></PhonePage>;
const Scan = () => <PhonePage><div className="relative min-h-[720px] px-5 pb-24 pt-5"><p className="eyebrow">Scan card</p><h2 className="text-2xl font-black">Point camera at QR</h2><div className="relative mt-6 h-96 overflow-hidden rounded-[2rem] bg-foreground shadow-hero"><Camera className="absolute left-1/2 top-1/2 h-20 w-20 -translate-x-1/2 -translate-y-1/2 text-background/50" /><div className="absolute inset-10 rounded-[1.5rem] border-2 border-accent" /><div className="animate-scan-line absolute left-10 right-10 h-0.5 bg-accent" /></div><Nav /></div></PhonePage>;
const Customers = () => <PhonePage><div className="relative min-h-[720px] px-5 pb-24 pt-5"><p className="eyebrow">Customers</p><h2 className="text-2xl font-black">Retention segments</h2><div className="mt-5 space-y-3">{[["Mia Chen", "Gold · 12 visits"], ["Oscar Reed", "At-risk · 41 days"], ["Ava Singh", "VIP · $420 spend"]].map(([name, meta]) => <div key={name} className="flex items-center justify-between rounded-2xl bg-card p-4 shadow-card"><div><p className="font-black">{name}</p><p className="text-xs text-muted-foreground">{meta}</p></div><ChevronRight className="h-4 w-4" /></div>)}</div><Nav /></div></PhonePage>;
const Campaign = () => <PhonePage><div className="relative min-h-[720px] px-5 pb-24 pt-5"><p className="eyebrow">Campaign studio</p><h2 className="text-2xl font-black">Launch a loyalty boost</h2><div className="mt-5 space-y-3">{[[Megaphone, "Double points afternoon", "Predicted +18% repeat visits"], [Gift, "Free pastry after 5 visits", "Best for coffee shops"], [WalletCards, "Win-back SMS", "Target 42 dormant customers"]].map(([Icon, title, body]) => <div key={String(title)} className="rounded-2xl bg-card p-4 shadow-card"><Icon className="h-5 w-5 text-primary" /><p className="mt-3 font-black">{String(title)}</p><p className="text-xs text-muted-foreground">{String(body)}</p></div>)}</div><Nav /></div></PhonePage>;
const Insights = () => <PhonePage><div className="relative min-h-[720px] px-5 pb-24 pt-5"><p className="eyebrow">Insights</p><h2 className="text-2xl font-black">Retention impact</h2><div className="mt-5 rounded-2xl bg-card p-5 shadow-card"><LineChart className="h-5 w-5 text-primary" /><div className="mt-5 flex h-40 items-end gap-3">{[45, 72, 58, 86, 68, 94].map((h, i) => <span key={i} className="flex-1 rounded-t-xl bg-gradient-primary" style={{ height: `${h}%` }} />)}</div></div><div className="mt-3 grid grid-cols-2 gap-3"><Metric label="Repeat lift" value="+21%" /><Metric label="Retained value" value="$3.2k" /></div><Nav /></div></PhonePage>;
const SettingsScreen = () => <PhonePage><div className="relative min-h-[720px] px-5 pb-24 pt-5"><p className="eyebrow">Settings</p><h2 className="text-2xl font-black">Business controls</h2><div className="mt-5 space-y-3">{[[CreditCard, "Growth plan"], [QrCode, "NFC & QR setup"], [CheckCircle2, "POS connected"], [Settings, "Profile settings"]].map(([Icon, label]) => <div key={String(label)} className="flex items-center gap-3 rounded-2xl bg-card p-4 shadow-card"><Icon className="h-5 w-5 text-primary" /><span className="font-bold">{String(label)}</span></div>)}</div><Nav /></div></PhonePage>;

export const MobileMerchantPrototype = ({ screenId }: MobileMerchantPrototypeProps) => {
  const screens: Record<string, JSX.Element> = { "merchant-login": <Login />, "merchant-dashboard": <Dashboard />, "merchant-add-points": <AddPoints />, "merchant-scan": <Scan />, "merchant-customers": <Customers />, "merchant-campaign": <Campaign />, "merchant-insights": <Insights />, "merchant-settings": <SettingsScreen /> };
  return screens[screenId] ?? screens["merchant-dashboard"];
};
